services:
  - type: web
    name: mcp-server
    env: node
    plan: free  
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000  
      - key: MONGO_URI
        sync: false   
      - key: OPENAI_API_KEY
        sync: false   
